#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          40

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

bspc rule -a Termite:termite -o node=@^1:^1:/
termite &

# autostart
feh --bg-fill /home/marekfs/Pictures/bg.jpg
xrdb -merge /home/marekfs/.cache/wal/colors.Xresources
compton --config /home/marekfs/.config/compton.conf -b
polybar example
